# Generated by Django 6.0.5 on 2026-05-25 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('facility_or_cost_center', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=12)),
                ('raw_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=32)),
                ('normalized_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=32)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('spend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(default=list)),
                ('suspicious_reasons', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for audit')], default='needs_review', max_length=24)),
                ('edited', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP procurement/fuel'), ('utility', 'Utility electricity'), ('travel', 'Corporate travel')], max_length=24)),
                ('name', models.CharField(max_length=160)),
                ('ingestion_method', models.CharField(max_length=80)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('source_system', models.CharField(max_length=120)),
                ('imported_by', models.CharField(default='analyst@breatheesg.com', max_length=120)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('suspicious_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('actor', models.CharField(max_length=120)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingestion.activityrow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activityrow',
            name='source_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_rows', to='ingestion.sourcebatch'),
        ),
        migrations.AddField(
            model_name='sourcebatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_batches', to='ingestion.tenant'),
        ),
        migrations.AddField(
            model_name='activityrow',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_rows', to='ingestion.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='activityrow',
            unique_together={('source_batch', 'external_id')},
        ),
    ]
